[[redirects]]
  from = "/2018/04/26/deploy-java-angular-one"
  to = "/angular-java-deploy"
  status = 301
  force = true

[[redirects]]
  from = "/2012/11/02/198/"
  to = "/persistence-eclipselink"
  status = 301
  force = true


